# Generated by Django 5.1.6 on 2025-02-07 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Empresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(max_length=14, unique=True, verbose_name="CNPJ"),
                ),
                (
                    "razaoSocial",
                    models.CharField(max_length=30, verbose_name="Razão Social"),
                ),
                (
                    "nomeFantasia",
                    models.CharField(max_length=30, verbose_name="Nome Fantasia"),
                ),
                (
                    "areaAtuacao",
                    models.CharField(max_length=30, verbose_name="Área de atuação"),
                ),
                (
                    "tempoAtuacaoMercado",
                    models.IntegerField(verbose_name="Tempo de Atuação no Mercado"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GestaoDePessoas",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "capitalSocial",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Capital Social"
                    ),
                ),
                (
                    "funcionarioCLT",
                    models.IntegerField(verbose_name="Funcionários CLT"),
                ),
                (
                    "funcionarioTercerizados",
                    models.IntegerField(verbose_name="Funcionários Terceirizados"),
                ),
                ("estagiario", models.IntegerField(verbose_name="Estagiários")),
                ("numSocios", models.IntegerField(verbose_name="Quantidade de Sócios")),
                ("socios", models.CharField(max_length=20, verbose_name="Sócios")),
            ],
        ),
        migrations.CreateModel(
            name="Faturamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ano", models.IntegerField(verbose_name="Ano")),
                (
                    "faturamento",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Faturamento Total Anual",
                    ),
                ),
                (
                    "empresa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faturamento",
                        to="incubadora.empresa",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FaturamentoMensal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mes",
                    models.IntegerField(
                        choices=[
                            (1, 1),
                            (2, 2),
                            (3, 3),
                            (4, 4),
                            (5, 5),
                            (6, 6),
                            (7, 7),
                            (8, 8),
                            (9, 9),
                            (10, 10),
                            (11, 11),
                            (12, 12),
                        ],
                        verbose_name="Mês",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Faturamento Mensal",
                    ),
                ),
                (
                    "faturamento",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faturamentos_mensais",
                        to="incubadora.faturamento",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Redes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                (
                    "insta",
                    models.URLField(blank=True, null=True, verbose_name="Instagram"),
                ),
                (
                    "facebook",
                    models.URLField(blank=True, null=True, verbose_name="Facebook"),
                ),
                (
                    "twitter",
                    models.URLField(blank=True, null=True, verbose_name="Twitter"),
                ),
                (
                    "linkedin",
                    models.URLField(blank=True, null=True, verbose_name="LinkedIn"),
                ),
                (
                    "zap",
                    models.CharField(
                        blank=True, max_length=15, null=True, verbose_name="WhatsApp"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "empresa",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redes",
                        to="incubadora.empresa",
                    ),
                ),
            ],
        ),
    ]
