# Generated by Django 5.1.6 on 2025-02-08 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("incubadora", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faturamentomensal",
            options={"ordering": ["-faturamento", "-mes"]},
        ),
    ]
