# Generated by Django 5.1.6 on 2025-02-07 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incubadora", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faturamento",
            name="empresa",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Empresa",
                to="incubadora.empresa",
            ),
        ),
        migrations.AlterField(
            model_name="faturamentomensal",
            name="faturamento",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Empresa",
                to="incubadora.faturamento",
            ),
        ),
    ]
