# Generated by Django 5.1.6 on 2025-02-08 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incubadora", "0002_alter_faturamento_empresa_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gestaodepessoas",
            name="empresa",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gestao_pessoas",
                to="incubadora.empresa",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="redes",
            name="empresa",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="redes",
                to="incubadora.empresa",
            ),
        ),
    ]
