# Generated by Django 5.1.6 on 2025-02-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("incubadora", "0002_alter_faturamentomensal_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gestaodepessoas",
            name="socios",
            field=models.CharField(max_length=200, verbose_name="Sócios"),
        ),
        migrations.AlterField(
            model_name="redes",
            name="website",
            field=models.URLField(blank=True, default=1, verbose_name="Website"),
            preserve_default=False,
        ),
    ]
